from time import sleep
import os


'''seg=0
whildef frame():e(seg<=20):
        os.system('cls')
    print(seg)
    time.sleep(1)
    seg+=1
    '''

s=0.1125

def frame1():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")


    sleep(s)
def frame2():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")

    sleep(s)
def frame3():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame4():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame5():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame6():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame7():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame8():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame9():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame10():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame11():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame12():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame13():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame14():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame15():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame16():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame17():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame18():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame19():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame20():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame21():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame22():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame23():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                  11111111111                           ")
    print("                                  11111111111                           ")
    print("                                  11111111111                           ")
    print("                                  11111111111                           ")
    print("                                  11111111111                           ")
    print("                                  11111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame24():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                  11111111111                           ")
    print("                                 111111111111                           ")
    print("                                 111111111111                           ")
    print("                                 111111111111                           ")
    print("                                 111111111111                           ")
    print("                                 111111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame25():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                  11111111111                           ")
    print("                                 111111111111                           ")
    print("                                1111111111111                           ")
    print("                                1111111111111                           ")
    print("                                1111111111111                           ")
    print("                                1111111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame26():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                  11111111111                           ")
    print("                                 111111111111                           ")
    print("                                1111111111111                           ")
    print("                               11111111111111                           ")
    print("                               11111111111111                           ")
    print("                               11111111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame27():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                  11111111111                           ")
    print("                                 111111111111                           ")
    print("                                1111111111111                           ")
    print("                               11111111111111                           ")
    print("                              111111111111111                           ")
    print("                              111111111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame28():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                  11111111111                           ")
    print("                                 111111111111                           ")
    print("                                1111111111111                           ")
    print("                               11111111111111                           ")
    print("                              111111111111111                           ")
    print("                             1111111111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")

    sleep(s)
def frame29():
    os.system('cls')
    print("                                                                        ")
    print("                                                                        ")
    print("                                  11111111111                           ")
    print("                                1111111111111                           ")
    print("                               11111111111111                           ")
    print("                              111111111111111                           ")
    print("                             1111111111111111                           ")
    print("                            11111111111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    print("                                   1111111111                           ")
    sleep(0.25)



while True:
    frame1()
    frame2()
    frame3()
    frame4()
    frame5()
    frame6()
    frame7()
    frame8()
    frame9()
    frame10()
    frame11()
    frame12()
    frame13()
    frame14()
    frame15()
    frame16()
    frame17()
    frame18()
    frame19()
    frame20()
    frame21()
    frame22()
    frame23()
    frame24()
    frame25()
    frame26()
    frame27()
    frame28()
    frame29()

    frame28()
    frame27()
    frame26()
    frame25()
    frame24()
    frame23()
    frame22()
    frame21()
    frame20()
    frame19()
    frame18()
    frame17()
    frame16()
    frame15()
    frame14()
    frame13()
    frame12()
    frame11()
    frame10()
    frame9()
    frame8()
    frame7()
    frame6()
    frame5()
    frame4()
    frame3()
    frame2()

